version: "3.8"

services:
  currency_convertor:
    build: 
      context: .
      args:
        ENV_STATE: ${ENV_STATE}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - .:/app
    user: "1000:1000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.currency-convertor.rule=Host(`currency-convertor.dixeam.com`)"
      - "traefik.http.routers.currency-convertor.entrypoints=web"
      - "traefik.http.services.currency-convertor.loadbalancer.server.port=8001"
    networks:
      - app-network
    env_file:
      - ".env"

networks:
  app-network:
    external: true